#!/usr/bin/env python3
"""
Convert doctor form votes into selection mapping image_key -> doctor_id.

Inputs:
- form_option_mapping.json (from luts_generate_form_images.py)
- votes CSV with columns: image_id, selected_option
- optional base selection JSON to preserve non-voted images

Output:
- selected_doctor_by_image.json (format expected by luts_04_select_masks.py)
"""
from __future__ import annotations

import argparse
import csv
import json
from pathlib import Path

from common import parse_json, write_json


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description="Convert form votes to selection mapping.")
    parser.add_argument(
        "--form-mapping-json",
        default="data/LUTS/Annotations/processed/form_review/form_option_mapping.json",
        help="Form option mapping JSON generated by luts_generate_form_images.py.",
    )
    parser.add_argument(
        "--votes-csv",
        default="data/LUTS/Annotations/processed/form_review/votes_template.csv",
        help="Votes CSV with selected_option filled.",
    )
    parser.add_argument(
        "--output-json",
        default="data/LUTS/Annotations/processed/selected_doctor_by_image.json",
        help="Output selection JSON (used by step 4).",
    )
    parser.add_argument(
        "--base-selection-json",
        default="",
        help=(
            "Optional existing selection JSON used as base map. "
            "If omitted and --preserve-existing is enabled, output-json is used when it exists."
        ),
    )
    parser.add_argument(
        "--preserve-existing",
        action="store_true",
        default=True,
        help="Merge voted selections into existing map (default: True).",
    )
    parser.add_argument(
        "--no-preserve-existing",
        dest="preserve_existing",
        action="store_false",
        help="Write only voted image selections (old behavior).",
    )
    parser.add_argument(
        "--strict",
        action="store_true",
        help="Fail on missing/invalid votes instead of skipping.",
    )
    return parser.parse_args()


def main() -> None:
    args = parse_args()

    with open(args.form_mapping_json, "r", encoding="utf-8") as f:
        mapping = json.load(f)

    items = mapping.get("items", []) if isinstance(mapping, dict) else []
    by_image_id = {str(i.get("image_id")): i for i in items if i.get("image_id")}

    votes = {}
    with open(args.votes_csv, "r", encoding="utf-8", newline="") as f:
        reader = csv.DictReader(f)
        for row in reader:
            image_id = str(row.get("image_id") or "").strip()
            selected = str(row.get("selected_option") or "").strip().upper()
            if image_id:
                votes[image_id] = selected

    base_selections: dict[str, str] = {}
    if args.preserve_existing:
        if args.base_selection_json:
            base_path = Path(args.base_selection_json)
        else:
            base_path = Path(args.output_json)
        if base_path.exists():
            payload = parse_json(base_path)
            if isinstance(payload, dict) and isinstance(payload.get("selections"), dict):
                base_selections = {
                    str(image_key): str(doctor_id)
                    for image_key, doctor_id in payload["selections"].items()
                }
            elif isinstance(payload, dict):
                base_selections = {
                    str(image_key): str(doctor_id) for image_key, doctor_id in payload.items()
                }
            else:
                raise SystemExit(f"Invalid selection mapping format in base JSON: {base_path}")

    selections: dict[str, str] = dict(base_selections)
    skipped = 0
    updates = 0
    additions = 0
    for image_id, item in by_image_id.items():
        image_key = str(item.get("image_key") or "")
        options = item.get("options", {}) or {}
        selected = votes.get(image_id, "")
        if not image_key or not selected or selected not in options:
            if args.strict:
                raise SystemExit(
                    f"Missing/invalid vote for {image_id}. selected_option='{selected}', "
                    f"valid={sorted(options.keys())}"
                )
            skipped += 1
            continue
        doctor_id = str(options[selected].get("doctor_id") or "")
        if not doctor_id:
            if args.strict:
                raise SystemExit(f"No doctor_id found for {image_id}/{selected}")
            skipped += 1
            continue
        previous = selections.get(image_key)
        if previous is None:
            additions += 1
        elif previous != doctor_id:
            updates += 1
        selections[image_key] = doctor_id

    if not selections:
        raise SystemExit("No valid selections produced from votes.")

    write_json(args.output_json, {"selections": selections})
    print(f"Wrote selection mapping: {args.output_json}")
    print(f"Selections: {len(selections)}")
    print(f"Base selections loaded: {len(base_selections)}")
    print(f"Selections updated from votes: {updates}")
    print(f"Selections added from votes: {additions}")
    print(f"Skipped: {skipped}")


if __name__ == "__main__":
    main()
